matrix:
  include:

    # Backend
    - language: java
      before_install: cd backend
      jdk: oraclejdk13

      script:
        - ./gradlew build --scan -s

      # Gradle Caching
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/


    # Frontend
    - language: node_js
      node_js: 12

      install:
        - cd frontend
        - npm install

      script:
        - npm run test
        - npm run test:e2e
