ignore:
  - "backend/**/LostCitiesApplication*"
  - "backend/**/web/**"
  - "backend/**/persistence/**"
  - "backend/**/application/dto/**"
  - "frontend/src/main.ts"
coverage:
  status:
    patch: off
