// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game.card;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Card_isWager_76d9baac33_Test {
    private static final int WAGER_CARD_VALUE = 0;
    private Card card;

    @BeforeEach
    public void setup() {
        card = new Card();
    }

    @Test
    public void testIsWagerTrue() {
        card.setValue(WAGER_CARD_VALUE);
        assertEquals(true, card.isWager());
    }

    @Test
    public void testIsWagerFalse() {
        card.setValue(WAGER_CARD_VALUE + 1);
        assertEquals(false, card.isWager());
    }
}
