// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game.card;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Objects;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Card_getColor_12de459bd2_Test {

    private Card card;

    @BeforeEach
    public void setup() {
        card = new Card();
    }

    @Test
    public void testGetColorWhenColorIsSet() {
        Color expectedColor = Color.RED;
        card.setColor(expectedColor);

        Color actualColor = card.getColor();

        assertEquals(expectedColor, actualColor, "Expected color to be RED, but it was not");
    }

    @Test
    public void testGetColorWhenColorIsNotSet() {
        Color actualColor = card.getColor();

        assertEquals(null, actualColor, "Expected color to be null, but it was not");
    }
}
