// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game.card;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import org.mockito.Mockito;
import java.util.Objects;

public class Card_wager_f10f1f3cba_Test {
    private Card testCard;
    private static final int WAGER_CARD_VALUE = -1;

    @BeforeEach
    public void setup() {
        testCard = Mockito.mock(Card.class);
    }

    @Test
    public void testWager_validColorAndInstance() {
        Color color = Color.RED;
        int instance = 1;
        Mockito.when(testCard.wager(color, instance)).thenReturn(new Card(color, WAGER_CARD_VALUE, instance));
        Card resultCard = testCard.wager(color, instance);
        Assertions.assertNotNull(resultCard);
        Assertions.assertEquals(color, resultCard.getColor());
        Assertions.assertEquals(WAGER_CARD_VALUE, resultCard.getValue());
        Assertions.assertEquals(instance, resultCard.getInstance());
    }

    @Test
    public void testWager_nullColor() {
        Color color = null;
        int instance = 1;
        Assertions.assertThrows(NullPointerException.class, () -> {
            testCard.wager(color, instance);
        });
    }
}
