// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game.card;

import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.Objects;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
@SpringBootTest
public class Card_fromString_13a732c567_Test {

    private Card card;

    @BeforeEach
    public void setup() {
        card = new Card();
    }

    @Test
    public void testFromString_validInput() {
        String cardString = "RED_2_3";
        Card expectedCard = new Card(Color.RED, 2, 3);
        Card actualCard = Card.fromString(cardString);
        assertEquals(expectedCard, actualCard);
    }

    @Test
    public void testFromString_nullInput() {
        String cardString = null;
        Card actualCard = Card.fromString(cardString);
        assertEquals(null, actualCard);
    }

    @Test
    public void testFromString_invalidInput() {
        String cardString = "RED_2";
        assertThrows(UnableToParseCardException.class, () -> Card.fromString(cardString));
    }

    @Test
    public void testFromString_nonNumericInput() {
        String cardString = "RED_TWO_3";
        assertThrows(UnableToParseCardException.class, () -> Card.fromString(cardString));
    }
}
