// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game.card;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Card_toString_ceffa8036e_Test {

    private Card card;

    @BeforeEach
    public void setup() {
        card = new Card();
    }

    @Test
    public void testToString_success() {
        card.setColor("Red");
        card.setValue("5");
        card.setInstance("1");
        String expectedOutput = "Red_5_1";
        assertEquals(expectedOutput, card.toString());
    }

    @Test
    public void testToString_emptyValues() {
        card.setColor("");
        card.setValue("");
        card.setInstance("");
        String expectedOutput = "__";
        assertEquals(expectedOutput, card.toString());
    }

    @Test
    public void testToString_nullValues() {
        card.setColor(null);
        card.setValue(null);
        card.setInstance(null);
        String expectedOutput = "null_null_null";
        assertEquals(expectedOutput, card.toString());
    }
}
