// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game.card;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Card_Card_cedb9bb140_Test {

    private Card testCard;

    @BeforeEach
    public void setUp() {
        testCard = new Card(Color.RED, 5);
    }

    @Test
    public void testCardConstructorWithValidInputs() {
        assertEquals(Color.RED, testCard.getColor());
        assertEquals(5, testCard.getValue());
        assertEquals(0, testCard.getInstance());
    }

    @Test
    public void testCardConstructorWithInvalidColor() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Card(null, 5);
        });

        String expectedMessage = "Color cannot be null";
        String actualMessage = exception.getMessage();
        assertTrue(actualMessage.contains(expectedMessage));
    }

    @Test
    public void testCardConstructorWithInvalidValue() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            new Card(Color.RED, -5);
        });

        String expectedMessage = "Value must be between 1 and 10";
        String actualMessage = exception.getMessage();
        assertTrue(actualMessage.contains(expectedMessage));
    }
}
