// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game.card;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Card_Card_e1c9fc397a_Test {

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testCardCreation() {
        Color color = Color.RED;
        int value = 5;
        int instance = 1;

        Card card = new Card(color, value, instance);

        assertEquals(color, card.getColor());
        assertEquals(value, card.getValue());
        assertEquals(instance, card.getInstance());
    }

    @Test
    public void testCardCreationWithInvalidValue() {
        Color color = Color.BLUE;
        int value = -1;  // Invalid value
        int instance = 2;

        assertThrows(IllegalArgumentException.class, () -> new Card(color, value, instance));
    }
}
