// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game.card;

import com.fasterxml.jackson.annotation.JsonIgnore;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import java.util.Objects;
import static org.junit.jupiter.api.Assertions.*;

public class Card_equals_f2d574000d_Test {

    private Card card1;
    private Card card2;
    private Card card3;

    @BeforeEach
    public void setUp() {
        card1 = new Card("instance1", "red", 7);
        card2 = new Card("instance1", "red", 7);
        card3 = new Card("instance2", "blue", 9);
    }

    @Test
    public void testEquals_SameObject() {
        assertTrue(card1.equals(card1));
    }

    @Test
    public void testEquals_IdenticalCards() {
        assertTrue(card1.equals(card2));
    }

    @Test
    public void testEquals_DifferentCards() {
        assertFalse(card1.equals(card3));
    }

    @Test
    public void testEquals_NullObject() {
        assertFalse(card1.equals(null));
    }

    @Test
    public void testEquals_DifferentClassObject() {
        Object obj = new Object();
        assertFalse(card1.equals(obj));
    }
}
