// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.board.GameBoard;
import com.lostcities.lostcities.domain.game.player.Player;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Game_getBoard_7540134dd7_Test {

    private Game game;
    private GameBoard gameBoard;

    @BeforeEach
    public void setUp() {
        Player player1 = Mockito.mock(Player.class);
        Player player2 = Mockito.mock(Player.class);
        gameBoard = Mockito.mock(GameBoard.class);
        game = new Game(player1, player2, gameBoard);
    }

    @Test
    public void testGetBoard_whenBoardIsSet() {
        assertEquals(gameBoard, game.getBoard());
    }

    @Test
    public void testGetBoard_whenBoardIsNull() {
        game = new Game();
        assertNull(game.getBoard());
    }
}
