// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.user.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.when;

public class Game_getCurrentTurnPlayer_9ba09ad10d_Test {

    @InjectMocks
    private Game game;

    @Mock
    private Player currentTurnPlayer;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetCurrentTurnPlayer_WhenPlayerIsPresent() {
        when(game.getCurrentTurnPlayer()).thenReturn(Optional.of(currentTurnPlayer));
        Optional<Player> result = game.getCurrentTurnPlayer();
        assertTrue(result.isPresent());
        assertEquals(currentTurnPlayer, result.get());
    }

    @Test
    public void testGetCurrentTurnPlayer_WhenPlayerIsNotPresent() {
        when(game.getCurrentTurnPlayer()).thenReturn(Optional.empty());
        Optional<Player> result = game.getCurrentTurnPlayer();
        assertTrue(result.isEmpty());
    }
}
