// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.player.Player;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Game_getPlayer1_7ee40b5628_Test {

    private Game game;

    @BeforeEach
    public void setUp() {
        game = new Game();
    }

    @Test
    public void testGetPlayer1_whenPlayer1Exists() {
        Player player1 = new Player();
        game.setPlayer1(player1);

        Player actualPlayer1 = game.getPlayer1();

        assertEquals(player1, actualPlayer1, "The returned player1 should be the same as the one set");
    }

    @Test
    public void testGetPlayer1_whenPlayer1NotSet() {
        Player actualPlayer1 = game.getPlayer1();

        assertNull(actualPlayer1, "The returned player1 should be null as it was not set");
    }
}
