// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.Player;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.MockitoAnnotations;

public class Game_getPlayer2_84364a9a31_Test {

    @InjectMocks
    private Game game;

    @Mock
    private Player player2;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        game.setPlayer2(player2);
    }

    @Test
    public void testGetPlayer2_success() {
        Player result = game.getPlayer2();
        Assertions.assertEquals(player2, result, "Player2 should be returned successfully");
    }

    @Test
    public void testGetPlayer2_noPlayer2Set() {
        game.setPlayer2(null);
        Player result = game.getPlayer2();
        Assertions.assertNull(result, "Null should be returned when no player2 is set");
    }
}
