// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.exception.GameNotStartedException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
public class Game_didStart_aea9d705e2_Test {

    private Game game;

    @BeforeEach
    public void setup() {
        game = new Game();
    }

    @Test
    public void testDidStart_whenStatusStarted() {
        game.setStatus(Game.Status.Started);
        assertTrue(game.didStart());
    }

    @Test
    public void testDidStart_whenStatusEnded() {
        game.setStatus(Game.Status.Ended);
        assertTrue(game.didStart());
    }

    @Test
    public void testDidStart_whenStatusNotStartedOrEnded() {
        game.setStatus(Game.Status.NotStarted);
        assertFalse(game.didStart());
    }
}
