// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import org.junit.jupiter.api.Test;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;

public class GameBoard_GameBoard_f854c37532_Test {

    @Test
    public void testGameBoardCreationWithDefaultConstructor() {
        GameBoard gameBoard = new GameBoard();

        assertNotNull(gameBoard, "GameBoard object should not be null");
        assertEquals(0, gameBoard.getExpeditions().size(), "Expeditions map should be empty");
    }

    @Test
    public void testGameBoardCreationWithCustomConstructor() {
        Map<Color, CardStack> expeditions = new HashMap<>();
        expeditions.put(Color.RED, mock(CardStack.class));
        expeditions.put(Color.GREEN, mock(CardStack.class));

        GameBoard gameBoard = new GameBoard(expeditions);

        assertNotNull(gameBoard, "GameBoard object should not be null");
        assertEquals(2, gameBoard.getExpeditions().size(), "Expeditions map should contain 2 elements");
    }
}
