// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.Deck;
import com.lostcities.lostcities.domain.game.exception.GameNotStartedException;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.*;

class Game_create_d87b44332c_Test {

    @Test
    public void testCreateWithValidParameters() {
        Player player1 = Mockito.mock(Player.class);
        Player player2 = Mockito.mock(Player.class);
        Game game = Game.create(123L, player1, player2);
        assertNotNull(game);
        assertEquals(123L, game.getRandomSeed());
        assertEquals(player1, game.getPlayer1());
        assertEquals(player2, game.getPlayer2());
    }

    @Test
    public void testCreateWithNullPlayers() {
        assertThrows(NullPointerException.class, () -> Game.create(123L, null, null));
    }

}
