// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Deck;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.when;

public class Game_getDeck_2fad4fc26c_Test {

    @InjectMocks
    private Game game;

    @Mock
    private Deck deck;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetDeck_whenDeckIsNotNull() {
        when(game.getDeck()).thenReturn(deck);
        Deck result = game.getDeck();
        assertNotNull(result);
    }

    @Test
    public void testGetDeck_whenDeckIsNull() {
        when(game.getDeck()).thenReturn(null);
        Deck result = game.getDeck();
        assertNull(result);
    }
}
