// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Deck;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Game_setDeck_37b2d839f9_Test {
    private Game game;

    @BeforeEach
    public void setup() {
        game = new Game();
    }

    @Test
    public void testSetDeck_withValidDeck() {
        Deck deck = new Deck();
        game.setDeck(deck);
        assertEquals(deck, game.getDeck());
    }

    @Test
    public void testSetDeck_withNullDeck() {
        assertThrows(NullPointerException.class, () -> game.setDeck(null));
    }
}
