// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.user.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.stream.Collectors;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class Game_getPlayersStream_e60af09616_Test {

    private Game game;
    private Player player1;
    private Player player2;

    @BeforeEach
    public void setUp() {
        game = new Game();
        player1 = new Player(new User("Alice"), game);
        player2 = new Player(new User("Bob"), game);
    }

    @Test
    public void testGetPlayersStream_allPlayersNotNull() {
        game.setPlayer1(player1);
        game.setPlayer2(player2);

        Stream<Player> playersStream = game.getPlayersStream();
        assertEquals(2, playersStream.count());
    }

    @Test
    public void testGetPlayersStream_somePlayersNull() {
        game.setPlayer1(player1);

        Stream<Player> playersStream = game.getPlayersStream();
        Player player = playersStream.collect(Collectors.toList()).get(0);
        assertEquals(player1, player);
    }

    @Test
    public void testGetPlayersStream_allPlayersNull() {
        Stream<Player> playersStream = game.getPlayersStream();
        assertTrue(playersStream.collect(Collectors.toList()).isEmpty());
    }
}
