// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.Deck;
import com.lostcities.lostcities.domain.game.exception.EmptyDeckException;
import com.lostcities.lostcities.domain.game.exception.GameNotStartedException;
import com.lostcities.lostcities.domain.game.exception.IllegalMoveException;
import com.lostcities.lostcities.domain.game.exception.NotPlayersTurnException;
import com.lostcities.lostcities.domain.user.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class Game_getMoves_943876a1ab_Test {
    private Game game;
    private List<Move> moves;

    @BeforeEach
    public void setup() {
        game = new Game();
        moves = new ArrayList<>();
        moves.add(new Move());
        moves.add(new Move());
        game.setMoves(moves);
    }

    @Test
    public void testGetMoves() {
        List<Move> result = game.getMoves();
        assertNotNull(result);
        assertEquals(2, result.size());
        assertEquals(moves, result);
    }

    @Test
    public void testGetMovesWhenNoMoves() {
        game.setMoves(new ArrayList<>());
        List<Move> result = game.getMoves();
        assertNotNull(result);
        assertTrue(result.isEmpty());
    }
}
