// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import java.util.HashMap;
import java.util.Map;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class GameBoard_getDiscardStacksMap_5cb36b91a9_Test {

    @Mock
    private GameBoard gameBoard;

    private Map<Color, CardStack> discardStacks;

    @Before
    public void setup() {
        discardStacks = new HashMap<>();
        discardStacks.put(Color.RED, new CardStack(Color.RED));
        discardStacks.put(Color.GREEN, new CardStack(Color.GREEN));

        when(gameBoard.getDiscardStacksMap()).thenReturn(discardStacks);
    }

    @Test
    public void testGetDiscardStacksMap_Success() {
        Map<Color, CardStack> result = gameBoard.getDiscardStacksMap();
        assertEquals(discardStacks, result);
    }

    @Test
    public void testGetDiscardStacksMap_EmptyMap() {
        when(gameBoard.getDiscardStacksMap()).thenReturn(new HashMap<>());
        Map<Color, CardStack> result = gameBoard.getDiscardStacksMap();
        assertEquals(new HashMap<>(), result);
    }
}
