// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Game_advancePlayerTurn_41f907ec88_Test {

    private Game game;
    private User player1;
    private User player2;

    @BeforeEach
    public void setUp() {
        player1 = new User();
        player1.setUsername("Player1");
        player2 = new User();
        player2.setUsername("Player2");
        game = new Game(player1, player2);
    }

    @Test
    public void testAdvancePlayerTurn_FromPlayer1ToPlayer2() {
        game.setCurrentTurnPlayer(player1);
        game.advancePlayerTurn();
        assertEquals(player2, game.getCurrentTurnPlayer());
    }

    @Test
    public void testAdvancePlayerTurn_FromPlayer2ToPlayer1() {
        game.setCurrentTurnPlayer(player2);
        game.advancePlayerTurn();
        assertEquals(player1, game.getCurrentTurnPlayer());
    }
}
