// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Game_toString_ceffa8036e_Test {

    @InjectMocks
    private Game game;

    @BeforeEach
    public void init() {
        MockitoAnnotations.initMocks(this);
        game.setId(1234);
        game.setRandomSeed(5678);
        game.setPlayer1(new User("player1"));
        game.setPlayer2(new User("player2"));
        game.setDeck(new Deck());
        game.setBoard(new Board());
        game.setStatus(GameStatus.IN_PROGRESS);
    }

    @Test
    public void testToString() {
        String expected = "Game{id=1234, randomSeed=5678, player1=User{name='player1'}, player2=User{name='player2'}, deck=Deck{cards=[]}, board=Board{cards=[]}, status=IN_PROGRESS}";
        String actual = game.toString();
        assertEquals(expected, actual);
    }

    @Test
    public void testToString_WithNullValues() {
        game.setPlayer1(null);
        game.setPlayer2(null);
        game.setDeck(null);
        game.setBoard(null);
        String expected = "Game{id=1234, randomSeed=5678, player1=null, player2=null, deck=null, board=null, status=IN_PROGRESS}";
        String actual = game.toString();
        assertEquals(expected, actual);
    }
}
