// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class GameInfo_getId_92e05748b6_Test {
    private GameInfo gameInfo;

    @BeforeEach
    public void setup() {
        gameInfo = new GameInfo();
    }

    @Test
    public void testGetId_positiveScenario() {
        gameInfo.setId(100);
        int actualId = gameInfo.getId();
        assertEquals(100, actualId, "Expected and actual ID don't match");
    }

    @Test
    public void testGetId_zeroIdScenario() {
        gameInfo.setId(0);
        int actualId = gameInfo.getId();
        assertEquals(0, actualId, "Expected and actual ID don't match");
    }
}
