// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class GameInfo_getPlayer1_da4571e74e_Test {

    @Mock
    GameInfo gameInfo;

    @BeforeEach
    public void setup() {
        Mockito.when(gameInfo.getPlayer1()).thenReturn(1);
    }

    @Test
    public void testGetPlayer1_success() {
        int player1 = gameInfo.getPlayer1();
        assertEquals(1, player1, "getPlayer1 should return 1");
    }

    @Test
    public void testGetPlayer1_failure() {
        Mockito.when(gameInfo.getPlayer1()).thenReturn(2);
        int player1 = gameInfo.getPlayer1();
        assertEquals(1, player1, "getPlayer1 should return 1 but returned " + player1);
    }
}
