// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Game_joinGameAsSecondPlayer_701e878751_Test {

    @Mock
    private Player player1;

    @Mock
    private Player player2;

    private Game game;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
        game = new Game(player1);
    }

    @Test
    public void testJoinGameAsSecondPlayer_Success() {
        game.joinGameAsSecondPlayer(player2);
        assertEquals(player2, game.getPlayer2());
        assertEquals(Status.ReadyToStart, game.getStatus());
    }

    @Test
    public void testJoinGameAsSecondPlayer_Failure() {
        assertThrows(IllegalArgumentException.class, () -> game.joinGameAsSecondPlayer(null));
    }
}
