// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
public class Game_create_e23e1b74a2_Test {

    @InjectMocks
    private Game game;

    @Mock
    private Player player1;

    @Mock
    private Player player2;

    @BeforeEach
    public void setup() {
        game = new Game();
        player1 = Mockito.mock(Player.class);
        player2 = Mockito.mock(Player.class);
    }

    @Test
    public void testCreateGameWithPlayer1() {
        Game createdGame = Game.create(123456, player1);
        assertNotNull(createdGame);
        assertEquals(player1, createdGame.getPlayer1());
        assertNull(createdGame.getPlayer2());
    }

    @Test
    public void testCreateGameWithNullPlayer() {
        Exception exception = assertThrows(NullPointerException.class, () -> {
            Game.create(123456, null);
        });
        assertEquals("Player1 should not be null", exception.getMessage());
    }

}
