// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(SpringExtension.class)
class GameInfo_getPlayer2_81ab29ab96_Test {

    @InjectMocks
    private Game game;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetPlayer2_Success() {
        int expectedPlayer2 = 2;
        game.setPlayer2(expectedPlayer2);
        int actualPlayer2 = game.getPlayer2();
        assertEquals(expectedPlayer2, actualPlayer2, "getPlayer2() did not return the expected player");
    }

    @Test
    public void testGetPlayer2_Failure() {
        int expectedPlayer2 = 3;
        game.setPlayer2(2);
        int actualPlayer2 = game.getPlayer2();
        assertNotEquals(expectedPlayer2, actualPlayer2, "getPlayer2() did not return the expected player");
    }
}
