// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

public class Game_Game_45fd9b9bbf_Test {

    private Game game;
    private Deck mockDeck;
    private GameBoard mockBoard;
    private Player mockPlayer1;
    private Player mockPlayer2;
    private long randomSeed;

    @BeforeEach
    public void setUp() {
        randomSeed = 123456789L;
        mockDeck = mock(Deck.class);
        mockBoard = mock(GameBoard.class);
        mockPlayer1 = mock(Player.class);
        mockPlayer2 = mock(Player.class);

        game = new Game(randomSeed, mockDeck, mockBoard, mockPlayer1, mockPlayer2);
    }

    @Test
    public void testGameConstructorWithValidParameters() {
        assertThat(game.getDeck()).isEqualTo(mockDeck);
        assertThat(game.getBoard()).isEqualTo(mockBoard);
        assertThat(game.getPlayer1()).isEqualTo(mockPlayer1);
        assertThat(game.getPlayer2()).isEqualTo(mockPlayer2);
        assertThat(game.getRandomSeed()).isEqualTo(randomSeed);
        assertThat(game.getStatus()).isEqualTo(Game.Status.New);
        assertThat(game.getMoves()).isNotNull();
    }

    @Test
    public void testGameConstructorWithNullDeck() {
        Game gameWithNullDeck = new Game(randomSeed, null, mockBoard, mockPlayer1, mockPlayer2);
        assertThat(gameWithNullDeck.getDeck()).isNull();
    }
}
