// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.Deck;
import com.lostcities.lostcities.domain.game.exception.EmptyDeckException;
import com.lostcities.lostcities.domain.game.exception.GameNotStartedException;
import com.lostcities.lostcities.domain.game.exception.IllegalMoveException;
import com.lostcities.lostcities.domain.game.exception.NotPlayersTurnException;
import com.lostcities.lostcities.domain.user.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Game_getStatus_2dd51d694b_Test {

    @Mock
    private Game game;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testGetStatus_WhenGameIsInProgress() {
        when(game.getStatus()).thenReturn(Status.IN_PROGRESS);
        Status s = game.getStatus();
        assertEquals(Status.IN_PROGRESS, s);
    }

    @Test
    public void testGetStatus_WhenGameHasEnded() {
        when(game.getStatus()).thenReturn(Status.ENDED);
        Status s = game.getStatus();
        assertEquals(Status.ENDED, s);
    }
}
