// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class GameInfo_GameInfo_aec08dd8d2_Test {

    private GameInfo gameInfo;

    @BeforeEach
    public void init() {
        gameInfo = new GameInfo(1, 2, 3);
    }

    @Test
    public void testGameInfoId() {
        assertEquals(1, gameInfo.getId(), "The ID should be 1");
    }

    @Test
    public void testGameInfoPlayer1() {
        assertEquals(2, gameInfo.getPlayer1(), "The Player1 should be 2");
    }

    @Test
    public void testGameInfoPlayer2() {
        assertEquals(3, gameInfo.getPlayer2(), "The Player2 should be 3");
    }
}
