// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Game_start_dfc002ef3f_Test {

    @InjectMocks
    private Game game;

    @Mock
    private Player player1;

    @Mock
    private Player player2;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testStart_InitialTurnPlayerIsPlayer1() {
        game.start();
        assertEquals(player1, game.getCurrentTurnPlayer());
    }

    @Test
    public void testStart_GameStatusIsStarted() {
        game.start();
        assertEquals(Status.Started, game.getStatus());
    }

    @Test
    public void testStart_StartingHandsAreDrawn() {
        when(player1.drawStartingHands()).thenReturn(true);
        when(player2.drawStartingHands()).thenReturn(true);
        game.start();
        assertEquals(true, player1.hasStartingHands());
        assertEquals(true, player2.hasStartingHands());
    }

    @Test
    public void testStart_StartingHandsAreNotDrawn() {
        when(player1.drawStartingHands()).thenReturn(false);
        when(player2.drawStartingHands()).thenReturn(false);
        game.start();
        assertEquals(false, player1.hasStartingHands());
        assertEquals(false, player2.hasStartingHands());
    }
}
