// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.exception.NotPlayersTurnException;
import com.lostcities.lostcities.domain.user.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import static org.mockito.Mockito.*;
import static org.junit.jupiter.api.Assertions.*;

public class Game_restoreState_c12aa89a16_Test {

    @Mock
    private Game game;

    @Mock
    private User player2;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testRestoreStateWithPlayer2NotNull() {
        doNothing().when(game).joinGameAsSecondPlayer(player2);
        when(game.didStart()).thenReturn(false);
        doNothing().when(game).reRunMoves();

        game.restoreState();

        verify(game, times(1)).joinGameAsSecondPlayer(player2);
        verify(game, times(0)).start();
        verify(game, times(1)).reRunMoves();
    }

    @Test
    public void testRestoreStateWithPlayer2Null() {
        when(game.getPlayer2()).thenReturn(null);
        when(game.didStart()).thenReturn(true);
        doNothing().when(game).start();
        doNothing().when(game).reRunMoves();

        game.restoreState();

        verify(game, times(0)).joinGameAsSecondPlayer(player2);
        verify(game, times(1)).start();
        verify(game, times(1)).reRunMoves();
    }

    @Test
    public void testRestoreStateThrowsException() {
        doNothing().when(game).joinGameAsSecondPlayer(player2);
        when(game.didStart()).thenReturn(true);
        doThrow(new NotPlayersTurnException()).when(game).start();

        assertThrows(NotPlayersTurnException.class, () -> game.restoreState());

        verify(game, times(1)).joinGameAsSecondPlayer(player2);
        verify(game, times(1)).start();
        verify(game, times(0)).reRunMoves();
    }
}
