// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Move_getFollowingStage_500605d9c4_Test {

    @Test
    public void testGetFollowingStage_FirstStage() {
        TurnStage currentStage = TurnStage.FIRST_STAGE;
        TurnStage nextStage = currentStage.getFollowingStage();
        assertEquals(TurnStage.SECOND_STAGE, nextStage);
    }

    @Test
    public void testGetFollowingStage_LastStage() {
        TurnStage currentStage = TurnStage.LAST_STAGE;
        TurnStage nextStage = currentStage.getFollowingStage();
        assertEquals(TurnStage.FIRST_STAGE, nextStage);
    }

    @Test
    public void testGetFollowingStage_MiddleStage() {
        TurnStage currentStage = TurnStage.MIDDLE_STAGE;
        TurnStage nextStage = currentStage.getFollowingStage();
        assertEquals(TurnStage.NEXT_MIDDLE_STAGE, nextStage);
    }
}
