// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.user.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Move_getUser_ce76c401a0_Test {

    private Move move;
    private User user;

    @BeforeEach
    public void setUp() {
        move = new Move();
        user = Mockito.mock(User.class);
    }

    @Test
    public void testGetUser_whenUserIsSet() {
        move.setUser(user);
        User result = move.getUser();
        assertEquals(user, result, "Expected and actual User should be the same");
    }

    @Test
    public void testGetUser_whenUserIsNotSet() {
        User result = move.getUser();
        assertNull(result, "Expected null when user is not set");
    }
}
