// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class Move_isFirstStage_7b168e8552_Test {
    private Move move;

    @BeforeEach
    void setUp() {
        move = new Move();
    }

    @Test
    public void testIsFirstStage_whenOrderIsFirstStage() {
        move.setOrder(Move.FIRST_STAGE.order);
        assertTrue(move.isFirstStage());
    }

    @Test
    public void testIsFirstStage_whenOrderIsNotFirstStage() {
        move.setOrder(Move.SECOND_STAGE.order);
        assertFalse(move.isFirstStage());
    }
}
