// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Move_getCard_a843875473_Test {
    private Move move;
    private Card card;

    @BeforeEach
    public void setUp() {
        card = new Card(Color.YELLOW, 7);
        move = new Move();
        move.setCard(card);
    }

    @Test
    public void testGetCardSuccess() {
        assertEquals(card, move.getCard());
    }

    @Test
    public void testGetCardFailure() {
        Card differentCard = new Card(Color.BLUE, 5);
        assertNotEquals(differentCard, move.getCard());
    }
}
