// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

@ExtendWith(MockitoExtension.class)
public class Move_setPlayer_53da14c203_Test {

    @Mock
    Player mockPlayer;

    @InjectMocks
    Move move;

    @BeforeEach
    public void setUp() {
        move = new Move();
    }

    @Test
    public void testSetPlayer_ValidPlayer() {
        move.setPlayer(mockPlayer);
        assertEquals(mockPlayer, move.getPlayer());
    }

    @Test
    public void testSetPlayer_NullPlayer() {
        move.setPlayer(null);
        assertNull(move.getPlayer());
    }
}
