// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.Player;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.mockito.Mockito.when;

public class Move_getPlayer_778f3da533_Test {

    @Mock
    private Move move;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testGetPlayer_whenPlayerExists() {
        Player player = new Player();
        player.setName("player1");
        when(move.getPlayer()).thenReturn(player);

        Player result = move.getPlayer();

        assertEquals(player, result, "Expected player does not match actual player");
    }

    @Test
    public void testGetPlayer_whenPlayerDoesNotExist() {
        when(move.getPlayer()).thenReturn(null);

        Player result = move.getPlayer();

        assertNull(result, "Expected null player but found a player");
    }
}
