// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.card.Deck;
import com.lostcities.lostcities.domain.game.exception.EmptyDeckException;
import com.lostcities.lostcities.domain.game.exception.EmptyDiscardException;
import com.lostcities.lostcities.domain.user.User;
import com.lostcities.lostcities.persistence.CardConverter;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
public class Move_Move_0a437cc8bc_Test {

    @InjectMocks
    private Move move;

    @Test
    public void testMoveConstructorWithValidInput() {
        Player player = new Player("Player1");
        Type type = Type.DRAW;
        Card card = new Card(Color.YELLOW, 6);
        Color color = Color.YELLOW;

        Move move = new Move(player, type, card, color);

        assertEquals(player, move.getPlayer());
        assertEquals(type, move.getType());
        assertEquals(card, move.getCard());
        assertEquals(color, move.getColor());
    }

    @Test
    public void testMoveConstructorWithNullPlayer() {
        assertThrows(NullPointerException.class, () -> {
            new Move(null, Type.DRAW, new Card(Color.YELLOW, 6), Color.YELLOW);
        });
    }

    @Test
    public void testMoveConstructorWithNullType() {
        Player player = new Player("Player1");
        assertThrows(NullPointerException.class, () -> {
            new Move(player, null, new Card(Color.YELLOW, 6), Color.YELLOW);
        });
    }
}
