// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.card.Deck;
import com.lostcities.lostcities.domain.game.exception.EmptyDeckException;
import com.lostcities.lostcities.domain.game.exception.EmptyDiscardException;
import com.lostcities.lostcities.domain.user.User;
import com.lostcities.lostcities.persistence.CardConverter;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Move_getStage_ca683fbea5_Test {

    @Test
    public void testGetStage_InitialStage() {
        Move move = new Move();
        TurnStage stage = TurnStage.INITIAL;
        move.setStage(stage);
        
        assertEquals(stage, move.getStage());
    }

    @Test
    public void testGetStage_PlayCardStage() {
        Move move = new Move();
        TurnStage stage = TurnStage.PLAY_CARD;
        move.setStage(stage);
        
        assertEquals(stage, move.getStage());
    }

    @Test
    public void testGetStage_DrawCardStage() {
        Move move = new Move();
        TurnStage stage = TurnStage.DRAW_CARD;
        move.setStage(stage);
        
        assertEquals(stage, move.getStage());
    }
}
