// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.Player;
import com.lostcities.lostcities.domain.game.Move;
import com.lostcities.lostcities.domain.game.Type;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class Move_create_6ea5b2e96c_Test {

    private Player player;
    private Type type;

    @BeforeEach
    void setUp() {
        player = new Player("testPlayer");
        type = Type.DRAW;
    }

    @Test
    void testCreateMoveWithValidInputs() {
        Move move = Move.create(player, type);
        assertNotNull(move, "Move object should not be null");
        assertEquals(player, move.getPlayer(), "Players should match");
        assertEquals(type, move.getType(), "Types should match");
    }

    @Test
    void testCreateMoveWithNullPlayer() {
        assertThrows(NullPointerException.class, () -> Move.create(null, type));
    }

    @Test
    void testCreateMoveWithNullType() {
        assertThrows(NullPointerException.class, () -> Move.create(player, null));
    }
}
