// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mock;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

public class Move_isLastStage_c16592fe12_Test {
    
    private Move move;

    @Mock
    private Stage LAST_STAGE;

    @BeforeEach
    public void setUp() {
        move = new Move();
    }

    @Test
    public void testIsLastStage_whenOrderEqualsLastStageOrder() {
        when(LAST_STAGE.getOrder()).thenReturn(5);
        move.setOrder(5); // TODO: Change the value to the expected order
        boolean result = move.isLastStage();
        assertEquals(true, result, "Expected the method to return true when order equals LAST_STAGE order");
    }

    @Test
    public void testIsLastStage_whenOrderNotEqualsLastStageOrder() {
        when(LAST_STAGE.getOrder()).thenReturn(5);
        move.setOrder(3); // TODO: Change the value to a different order
        boolean result = move.isLastStage();
        assertEquals(false, result, "Expected the method to return false when order does not equal LAST_STAGE order");
    }
}
