// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.card.Deck;
import com.lostcities.lostcities.domain.game.exception.EmptyDeckException;
import com.lostcities.lostcities.domain.game.exception.EmptyDiscardException;
import com.lostcities.lostcities.domain.user.User;
import com.lostcities.lostcities.persistence.CardConverter;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Transient;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class Move_doesTurnMatter_bffbe2a6be_Test {

    @Test
    public void testDoesTurnMatter_whenTypeIsReadyToStart() {
        Move move = new Move();
        move.setType(Move.Type.ReadyToStart);
        Assertions.assertFalse(move.doesTurnMatter());
    }

    @Test
    public void testDoesTurnMatter_whenTypeIsNotReadyToStart() {
        Move move = new Move();
        move.setType(Move.Type.DrawFromDeck);
        Assertions.assertTrue(move.doesTurnMatter());
    }
}
