// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class Move_doesEndTurn_502f3d85b9_Test {

    @Mock
    MoveType type;

    @Mock
    Stage stage;

    Move move;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
        move = new Move();
        move.setType(type);
    }

    @Test
    void doesEndTurn_lastStage_true() {
        when(type.getStage()).thenReturn(stage);
        when(stage.isLastStage()).thenReturn(true);

        boolean result = move.doesEndTurn();

        assertTrue(result);
        verify(type, times(1)).getStage();
        verify(stage, times(1)).isLastStage();
    }

    @Test
    void doesEndTurn_notLastStage_false() {
        when(type.getStage()).thenReturn(stage);
        when(stage.isLastStage()).thenReturn(false);

        boolean result = move.doesEndTurn();

        assertFalse(result);
        verify(type, times(1)).getStage();
        verify(stage, times(1)).isLastStage();
    }
}
