// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.exception.EmptyDeckException;
import com.lostcities.lostcities.domain.game.exception.EmptyDiscardException;
import com.lostcities.lostcities.domain.user.User;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;

@RunWith(MockitoJUnitRunner.class)
public class Move_isDrawingCardJustDiscarded_521db1873e_Test {

    private Move moveUnderTest;
    private Move previousMove;

    @Before
    public void setUp() {
        moveUnderTest = new Move();
        previousMove = new Move();
    }

    @Test
    public void testIsDrawingCardJustDiscarded_True() {
        // Setup
        moveUnderTest.setType(Move.Type.DrawDiscard);
        moveUnderTest.setColor(Color.BLUE);
        previousMove.setType(Move.Type.DiscardCard);
        previousMove.setCard(new Card(Color.BLUE, 9));

        // Run the test
        final boolean result = moveUnderTest.isDrawingCardJustDiscarded(previousMove);

        // Verify the results
        assertEquals(true, result);
    }

    @Test
    public void testIsDrawingCardJustDiscarded_False() {
        // Setup
        moveUnderTest.setType(Move.Type.DrawDeck);
        moveUnderTest.setColor(Color.YELLOW);
        previousMove.setType(Move.Type.DiscardCard);
        previousMove.setCard(new Card(Color.BLUE, 9));

        // Run the test
        final boolean result = moveUnderTest.isDrawingCardJustDiscarded(previousMove);

        // Verify the results
        assertEquals(false, result);
    }
}
