// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.user.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

public class Move_setUser_e2a2590c5f_Test {
    private Move move;

    @Mock
    private User user;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
        move = new Move();
    }

    @Test
    public void testSetUser() {
        move.setUser(user);
        assertEquals(user, move.getUser());
    }

    @Test
    public void testSetUserNull() {
        move.setUser(null);
        assertNull(move.getUser());
    }
}
