// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.Game;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.runners.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class Move_setGame_d31d4d75c6_Test {

    @Mock
    private Game mockedGame;

    private Move move;

    @Before
    public void setup() {
        move = new Move();
    }

    @Test
    public void testSetGame_WhenGameIsNotNull() {
        when(mockedGame.getId()).thenReturn(1L);
        move.setGame(mockedGame);
        assertEquals(mockedGame, move.getGame());
    }

    @Test(expected = NullPointerException.class)
    public void testSetGame_WhenGameIsNull() {
        move.setGame(null);
    }
}
