// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Color;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Move_getColor_12de459bd2_Test {

    private Move move;

    @BeforeEach
    public void setUp() {
        move = new Move();
    }

    @Test
    public void testGetColorWhenColorIsSet() {
        // Set a color to the move
        move.setColor(Color.YELLOW);
        // Assert that the color returned is the one that was set
        Assertions.assertEquals(Color.YELLOW, move.getColor());
    }

    @Test
    public void testGetColorWhenColorIsNotSet() {
        // Assert that the color is null when no color has been set
        Assertions.assertNull(move.getColor());
    }
}
