// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.exception.CardLowerValueException;
import com.lostcities.lostcities.domain.game.exception.CardNotInHandException;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import java.util.LinkedHashSet;
import java.util.Set;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

@RunWith(MockitoJUnitRunner.class)
public class Player_addToHand_db011007a2_Test {

    private Player player;
    private Set<Card> hand;

    @Before
    public void setUp() {
        player = new Player("testPlayer");
        hand = new LinkedHashSet<>();
    }

    @Test
    public void testAddToHand_success() {
        Card card = new Card(Color.RED, 9);
        player.addToHand(card);
        assertEquals(1, player.getHand().size());
        assertTrue(player.getHand().contains(card));
    }

    @Test(expected = NullPointerException.class)
    public void testAddToHand_nullCard() {
        Card card = null;
        player.addToHand(card);
    }
}
