// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.exception.CardLowerValueException;
import com.lostcities.lostcities.domain.game.exception.CardNotInHandException;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mock;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;
import static org.mockito.MockitoAnnotations.initMocks;

public class Player_getInPlay_2b4f429882_Test {

    @Mock
    private Player player;

    private Map<Color, CardStack> inPlay;

    @Before
    public void setUp() {
        initMocks(this);

        inPlay = new HashMap<>();
        inPlay.put(Color.RED, new CardStack(Color.RED));
        inPlay.put(Color.GREEN, new CardStack(Color.GREEN));

        when(player.getInPlay()).thenReturn(inPlay);
    }

    @Test
    public void testGetInPlaySuccess() {
        Map<Color, CardStack> result = player.getInPlay();
        assertEquals(inPlay, result);
    }

    @Test
    public void testGetInPlayEmpty() {
        inPlay.clear();
        Map<Color, CardStack> result = player.getInPlay();
        assertEquals(inPlay, result);
    }
}
