// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;
import java.util.Objects;

public class Player_hashCode_5a2657087a_Test {

    private Player player;

    @BeforeEach
    public void setup() {
        player = new Player();
    }

    @Test
    public void testHashCodeWithNonNullId() {
        player.setId("123");
        int expected = Objects.hash("123");
        Assertions.assertEquals(expected, player.hashCode());
    }

    @Test
    public void testHashCodeWithNullId() {
        player.setId(null);
        int expected = Objects.hash((Object) null);
        Assertions.assertEquals(expected, player.hashCode());
    }
}
