// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.exception.CardLowerValueException;
import com.lostcities.lostcities.domain.game.exception.CardNotInHandException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.util.HashSet;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

public class Player_removeFromHand_524ea1182a_Test {

    private Player testPlayer;
    private Set<Card> hand;

    @BeforeEach
    public void setup() {
        testPlayer = new Player("testPlayer");
        hand = new HashSet<>();
        testPlayer.setHand(hand);
    }

    @Test
    public void testRemoveFromHand_cardInHand() {
        Card card = new Card(Color.RED, 5);
        hand.add(card);

        testPlayer.removeFromHand(card);

        assertFalse(hand.contains(card));
    }

    @Test
    public void testRemoveFromHand_cardNotInHand() {
        Card card = new Card(Color.RED, 5);

        assertThrows(CardNotInHandException.class, () -> testPlayer.removeFromHand(card));
    }
}
