// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class Player_getInPlay_98ab1c9e8a_Test {

    @InjectMocks
    private Player player;

    @Mock
    private Map<Color, CardStack> inPlay;

    private CardStack redCardStack = new CardStack();

    @Before
    public void setUp() {
        redCardStack.addCard(new Card(Color.RED, 9));
        when(inPlay.get(Color.RED)).thenReturn(redCardStack);
    }

    @Test
    public void testGetInPlay_Success() {
        CardStack result = player.getInPlay(Color.RED);
        assertEquals(redCardStack, result);
    }

    @Test
    public void testGetInPlay_Null() {
        CardStack result = player.getInPlay(Color.YELLOW);
        assertEquals(null, result);
    }
}
