// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.exception.CardLowerValueException;
import com.lostcities.lostcities.domain.game.exception.CardNotInHandException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class Player_play_55293e8a48_Test {

    @InjectMocks
    private Player player;

    @Mock
    private CardStack cardStack;

    @Mock
    private Card card;

    @BeforeEach
    void setUp() {
        player = new Player("TestPlayer");
    }

    @Test
    void testPlayCardSuccess() {
        when(card.getColor()).thenReturn(Color.RED);
        doNothing().when(cardStack).addToTop(any(Card.class));

        player.play(card);

        verify(card, times(1)).getColor();
        verify(cardStack, times(1)).addToTop(card);
    }

    @Test
    void testPlayCardNotInHandException() {
        when(card.getColor()).thenReturn(Color.RED);
        doThrow(new CardNotInHandException()).when(cardStack).addToTop(card);

        assertThrows(CardNotInHandException.class, () -> player.play(card));
    }

    @Test
    void testPlayCardLowerValueException() {
        when(card.getColor()).thenReturn(Color.RED);
        doThrow(new CardLowerValueException()).when(cardStack).addToTop(card);

        assertThrows(CardLowerValueException.class, () -> player.play(card));
    }
}
