// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(MockitoExtension.class)
public class Player_isReadyToStart_1db7011575_Test {

    @InjectMocks
    private Player player;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testIsReadyToStart_True() {
        player.setReadyToStart(true);
        assertTrue(player.isReadyToStart());
    }

    @Test
    public void testIsReadyToStart_False() {
        player.setReadyToStart(false);
        assertFalse(player.isReadyToStart());
    }
}
