// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.Color;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;
import java.util.HashSet;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class Player_hasCard_9148c5e865_Test {
    private Player player;
    private HashSet<Card> hand;

    @Before
    public void setUp() {
        player = new Player();
        hand = Mockito.mock(HashSet.class);
        player.setHand(hand);
    }

    @Test
    public void testHasCardTrue() {
        Card card = new Card(Color.YELLOW, 5);
        Mockito.when(hand.contains(card)).thenReturn(true);
        assertTrue(player.hasCard(card));
    }

    @Test
    public void testHasCardFalse() {
        Card card = new Card(Color.YELLOW, 5);
        Mockito.when(hand.contains(card)).thenReturn(false);
        assertFalse(player.hasCard(card));
    }
}
