// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import com.lostcities.lostcities.domain.game.exception.CardLowerValueException;
import com.lostcities.lostcities.domain.game.exception.CardNotInHandException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.*;

import java.util.HashSet;
import java.util.Set;

@ExtendWith(MockitoExtension.class)
public class Player_getHand_01ac40f643_Test {

    @Mock
    private Player player;

    private Set<Card> hand;

    @BeforeEach
    public void setUp() {
        hand = new HashSet<>();
        when(player.getHand()).thenReturn(hand);
    }

    @Test
    public void testGetHand_whenHandIsEmpty() {
        assertEquals(hand, player.getHand(), "Expected empty hand");
    }

    @Test
    public void testGetHand_whenHandIsNotEmpty() {
        Card testCard = new Card(Color.RED, 5);
        hand.add(testCard);
        assertEquals(hand, player.getHand(), "Expected hand with one card");
    }
}
