// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Player_getName_8400ac6fb7_Test {

    private Player player;

    @Mock
    private String name;

    @BeforeEach
    public void setUp(){
        MockitoAnnotations.initMocks(this);
        player = new Player(name);
    }

    @Test
    public void testGetName(){
        assertEquals(name, player.getName());
    }

    @Test
    public void testGetNameWithDifferentName(){
        String differentName = "Different Name";
        player = new Player(differentName);
        assertEquals(differentName, player.getName());
    }
}
