// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class Player_getId_3d7d4d4e1a_Test {

    private Player player;

    @BeforeEach
    public void setup() {
        player = new Player();
    }

    @Test
    public void testGetIdSuccess() {
        long expectedId = 12345L;
        player.setId(expectedId);
        assertEquals(expectedId, player.getId(), "IDs should match");
    }

    @Test
    public void testGetIdDefault() {
        long defaultId = 0L;
        assertEquals(defaultId, player.getId(), "Default ID should be 0");
    }
}
