// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import com.lostcities.lostcities.domain.game.card.Card;
import com.lostcities.lostcities.domain.game.card.CardStack;
import com.lostcities.lostcities.domain.game.card.Color;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class Player_initializeInPlayMap_eaf744c1c0_Test {

    private Player player;

    @BeforeEach
    public void setUp() {
        player = new Player();
    }

    @Test
    public void testInitializeInPlayMap() {
        player.initializeInPlayMap();
        Map<Color, CardStack> inPlay = player.getInPlay();
        assertNotNull(inPlay);
        assertEquals(5, inPlay.size()); // assuming there are 5 colors
        for(var color : Color.values()) {
            CardStack stack = inPlay.get(color);
            assertNotNull(stack);
            assertEquals(0, stack.size());
        }
    }

    @Test
    public void testInitializeInPlayMap_noDuplicateColors() {
        player.initializeInPlayMap();
        Map<Color, CardStack> inPlay = player.getInPlay();
        Map<Color, CardStack> comparisonMap = new HashMap<>();
        for(var color : Color.values()) {
            comparisonMap.put(color, new CardStack());
        }
        assertEquals(comparisonMap, inPlay);
    }
}
