// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.domain.game;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class Player_setReadyToStart_27e6eaa08d_Test {

    private Player player;

    @BeforeEach
    public void setUp() {
        player = new Player();
    }

    @Test
    public void testSetReadyToStart_True() {
        player.setReadyToStart(true);
        assertTrue(player.isReadyToStart());
    }

    @Test
    public void testSetReadyToStart_False() {
        player.setReadyToStart(false);
        assertFalse(player.isReadyToStart());
    }
}
