// Test generated by RoostGPT for test java-unit-test-bhavya using AI Type Open AI and AI Model gpt-4

package com.lostcities.lostcities.application.service;

import com.lostcities.lostcities.domain.game.Game;
import com.lostcities.lostcities.domain.game.GameRepository;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;
import java.util.Optional;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThrows;
import static org.mockito.Mockito.when;

@RunWith(MockitoJUnitRunner.class)
public class GameService_getGameById_678d51144b_Test {

    @Mock
    private GameRepository gameRepository;

    @InjectMocks
    private GameService gameService;

    private Game game;

    @Before
    public void setUp() {
        game = new Game();
        game.setId(1L);
    }

    @Test
    public void testGetGameById_Success() {
        when(gameRepository.findById(1L)).thenReturn(Optional.of(game));
        Game actualGame = gameService.getGameById(1L);
        assertEquals(game, actualGame);
    }

    @Test
    public void testGetGameById_Failure() {
        when(gameRepository.findById(2L)).thenReturn(Optional.empty());
        Exception exception = assertThrows(RuntimeException.class, () -> {
            gameService.getGameById(2L);
        });
        String expectedMessage = "Game does not exist";
        String actualMessage = exception.getMessage();
        assertEquals(expectedMessage, actualMessage);
    }
}
